export const ROUTES = {
  NO_PATH: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  LEADERBOARD: "/leaderboard",
  CONTACT: "/contact",
  STUDENT_DASHBOARD: "/student/dashboard",
  STUDENT_QUIZ_SETS_LISTING: "/student/quiz/listing",
  STUDENT_START_QUIZ: "/student/quiz/start",
  STUDENT_RESULT: "/student/result",
  TEACHER_DASHBOARD: "/teacher/dashboard",
  TEACHER_QUIZ_CREATE: "/teacher/quiz/create",
  TEACHER_QUIZ_MANAGE: "/teacher/quiz/manage",
  TEACHER_ALL_QUIZSETS: "/teacher/quiz",
  TEACHER_QUESTIONS_ADD: "/teacher/quiz/questions-add",
};
